spring:
  application:
    name: routick

  datasource:
    url: jdbc:postgresql://localhost:5432/routick
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${JWT_SECRET}
  access-expiration-ms: 3600000      # 1??
  refresh-expiration-ms: 2592000000  # 30?

agent:
  base-url: http://localhost:8000
  mock: false
  timeout-seconds: 60

file:
  upload-dir: ./uploads   # ??? ?? ?? ??